version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    target-branch: 'main'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'npm dependencies'
